/* Generated by tools/gen_app_icons.py -- do not edit by hand. */
#pragma once
#include "lvgl.h"

/* Custom app-icon image for an icon-name key, or NULL if none. */
const lv_image_dsc_t *launcher_app_image(const char *key);
