#!/usr/bin/env bash
# Package a built launcher into a release archive.
#
#   tools/package_firmware.sh v0.1.0
#
# Produces dist/esp32-launcher-<version>.zip containing every binary a
# complete flash needs, the flashing script, and a MANIFEST recording what
# it was built from.
#
# Offsets and the file list are read from launcher/build/flasher_args.json
# rather than hardcoded. That file is generated by the build, so the archive
# cannot drift from the partition table the way a hand-maintained list does
# -- which is how the old firmware/bin/ ended up shipping without
# srmodels.bin, leaving voice non-functional on every board flashed from it.
set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
    echo "usage: tools/package_firmware.sh <version>   (e.g. v0.1.0)" >&2
    exit 2
fi

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$REPO/launcher/build"
ARGS="$BUILD/flasher_args.json"
OUT="$REPO/dist/esp32-launcher-$VERSION"

if [ ! -f "$ARGS" ]; then
    echo "no build found at $BUILD -- run 'idf.py build' in launcher/ first" >&2
    exit 1
fi

command -v zip >/dev/null || { echo "zip is required but not installed" >&2; exit 1; }

# IDF version for the MANIFEST. In CI the toolchain lives in the build
# container, not ~/esp, so accept it from the environment first and only
# then fall back to probing a local install. Each step is guarded: this
# script runs under `set -e` and a missing export.sh must not abort it.
IDF_VER="${IDF_VERSION:-}"
if [ -z "$IDF_VER" ] && command -v idf.py >/dev/null 2>&1; then
    IDF_VER=$(idf.py --version 2>/dev/null | tail -1 || true)
fi
if [ -z "$IDF_VER" ] && [ -f "$HOME/esp/esp-idf/export.sh" ]; then
    IDF_VER=$( . "$HOME/esp/esp-idf/export.sh" >/dev/null 2>&1 || true
               idf.py --version 2>/dev/null | tail -1 || true )
fi
IDF_VER="${IDF_VER:-unknown}"

rm -rf "$OUT"
mkdir -p "$OUT/bin"

# Copy each flash file to a flat name, and emit the offset table alongside.
python3 - "$ARGS" "$BUILD" "$OUT" <<'PY'
import json, os, shutil, sys, hashlib
args_path, build, out = sys.argv[1:4]
d = json.load(open(args_path))

rows = []
for off, rel in sorted(d["flash_files"].items(), key=lambda kv: int(kv[0], 16)):
    src = os.path.join(build, rel)
    flat = os.path.basename(rel)
    shutil.copy2(src, os.path.join(out, "bin", flat))
    digest = hashlib.sha256(open(src, "rb").read()).hexdigest()
    rows.append((off, flat, os.path.getsize(src), digest))

# OFFSETS is sourced by flash.sh: one "offset file" pair per line, in
# ascending offset order.
with open(os.path.join(out, "bin", "OFFSETS"), "w") as f:
    for off, flat, _, _ in rows:
        f.write(f"{off} {flat}\n")

# The write_flash flags the build actually used -- not a guess. The old
# flash.sh hardcoded --flash_mode dio, which is right here but would
# silently diverge if sdkconfig ever changed.
with open(os.path.join(out, "bin", "FLASH_ARGS"), "w") as f:
    f.write(" ".join(d["write_flash_args"]) + "\n")

with open(os.path.join(out, "SHA256SUMS"), "w") as f:
    for _, flat, _, digest in rows:
        f.write(f"{digest}  bin/{flat}\n")

print("\n".join(f"  {o:>10}  {n:<24} {s:>10,} bytes" for o, n, s, _ in rows))
PY

# MANIFEST: what this was built from, so a board can be traced back to a commit.
{
    echo "version=$VERSION"
    echo "commit=$(git -C "$REPO" rev-parse --short HEAD)"
    echo "commit_full=$(git -C "$REPO" rev-parse HEAD)"
    echo "dirty=$(if [ -n "$(git -C "$REPO" status --porcelain)" ]; then echo yes; else echo no; fi)"
    echo "built_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "idf=$IDF_VER"
} > "$OUT/MANIFEST"

cp "$REPO/firmware/flash.sh" "$OUT/flash.sh"
chmod +x "$OUT/flash.sh"
cp "$REPO/firmware/README.md" "$OUT/README.md"

( cd "$REPO/dist" && zip -qr "esp32-launcher-$VERSION.zip" "esp32-launcher-$VERSION" )

echo
echo "MANIFEST:"; sed 's/^/  /' "$OUT/MANIFEST"
echo
echo "wrote dist/esp32-launcher-$VERSION.zip ($(du -h "$REPO/dist/esp32-launcher-$VERSION.zip" | cut -f1))"
